import type { NextPage } from 'next'
import Head from 'next/head'

import ServicesOverView from '~/feature/landing/ServicesOverView'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Glowlabs - Spa and Salon</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="my-36">
				<ServicesOverView />
			</main>
		</>
	)
}

export default Home
