import type { NextPage } from 'next'
import Head from 'next/head'

import Topnav from '~/feature/landing/Topnav'
import { trpc } from '~/utils/trpc'

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: 'from tRPC' })

  return (
    <>
      <Head>
        <title>Glowlabs - Spa and Salon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Topnav />
      </main>
    </>
  )
}

export default Home
